// ProjectData.jsx
const projects = [
  {
    title: "Project 1",
    href: "/project1",
    description: "Description of project 1.",
    dates: "Jan 2023 - Present",
    tags: ["React", "JavaScript"],
    link: "https://example.com",
    image: "https://nextui.org/images/hero-card-complete.jpeg",
    video: null,
    links: [{ icon: "🌐", type: "Website", href: "https://example.com" }],
  },
  {
    title: "Project 2",
    href: "/project2",
    description: "Description of project 2.",
    dates: "Feb 2023 - Present",
    tags: ["Node.js", "Express"],
    link: "https://example.com",
    image: "https://nextui.org/images/hero-card-complete.jpeg",
    video: null,
    links: [{ icon: "🌐", type: "Website", href: "https://example.com" }],
  },
  {
    title: "Project 3",
    href: "/project3",
    description: "Description of project 3.",
    dates: "Mar 2023 - Present",
    tags: ["Python", "Django"],
    link: "https://example.com",
    image: "https://nextui.org/images/hero-card-complete.jpeg",
    video: null,
    links: [{ icon: "🌐", type: "Website", href: "https://example.com" }],
  },
  {
    title: "Project 4",
    href: "/project4",
    description: "Description of project 4.",
    dates: "Apr 2023 - Present",
    tags: ["HTML", "CSS"],
    link: "https://example.com",
    image: "https://nextui.org/images/hero-card-complete.jpeg",
    video: null,
    links: [{ icon: "🌐", type: "Website", href: "https://example.com" }],
  },
  {
    title: "Project 5",
    href: "/project5",
    description: "Description of project 5.",
    dates: "May 2023 - Present",
    tags: ["Java", "Spring"],
    link: "https://example.com",
    image: "https://nextui.org/images/hero-card-complete.jpeg",
    video: null,
    links: [{ icon: "🌐", type: "Website", href: "https://example.com" }],
  },
  {
    title: "Project 6",
    href: "/project6",
    description: "Description of project 6.",
    dates: "Jun 2023 - Present",
    tags: ["PHP", "Laravel"],
    link: "https://example.com",
    image: "https://nextui.org/images/hero-card-complete.jpeg",
    video: null,
    links: [{ icon: "🌐", type: "Website", href: "https://example.com" }],
  },
];

export default projects;
